// <auto-generated />

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ModMail.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AstralModMail.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220128175045_AddedThreadsSet")]
    partial class AddedThreadsSet
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AstralModMail.Data.GuildEntity", b =>
                {
                    b.Property<decimal>("GuildId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("Category")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("Log")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("GuildId");

                    b.ToTable("Guilds");
                });

            modelBuilder.Entity("AstralModMail.Data.ThreadEntity", b =>
                {
                    b.Property<decimal>("Channel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("Guild")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("Recipient")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("Channel");

                    b.HasIndex("Guild");

                    b.ToTable("Threads");
                });

            modelBuilder.Entity("AstralModMail.Data.ThreadEntity", b =>
                {
                    b.HasOne("AstralModMail.Data.GuildEntity", "GuildEntity")
                        .WithMany("Threads")
                        .HasForeignKey("Guild")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GuildEntity");
                });

            modelBuilder.Entity("AstralModMail.Data.GuildEntity", b =>
                {
                    b.Navigation("Threads");
                });
#pragma warning restore 612, 618
        }
    }
}
